version: "3.3"

services:
  db:
    image: "postgres:14.2"
    ports:
      - "5444:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books