version: "3.3"

services:
  db:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: