/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.books.app.view;


import com.books.app.controller.BookImportCSVController;
import lombok.Getter;

/**
 * @author operador
 */
@Getter
public class BookImportCSVView extends javax.swing.JInternalFrame {

    private final BookImportCSVController csvController;

    /**
     * Creates new form BookImportCSVView
     */
    public BookImportCSVView() {
        initComponents();
        this.csvController = new BookImportCSVController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOpenExampleButton = new javax.swing.JButton();
        jSelectFileButton = new javax.swing.JButton();
        jScrollPanel = new javax.swing.JScrollPane();
        jListTable = new javax.swing.JTable();
        jSaveButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Importar CSV");

        jOpenExampleButton.setText("Abrir CSV de exemplo");
        jOpenExampleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenExampleButtonActionPerformed(evt);
            }
        });

        jSelectFileButton.setText("Selecionar arquivo para importação");
        jSelectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectFileButtonActionPerformed(evt);
            }
        });

        jListTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPanel.setViewportView(jListTable);

        jSaveButton.setText("Salvar Livros");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSaveButton)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSelectFileButton)
                                                .addComponent(jOpenExampleButton)
                                                .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jOpenExampleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSelectFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOpenExampleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenExampleButtonActionPerformed
        csvController.openExample();
    }//GEN-LAST:event_jOpenExampleButtonActionPerformed

    private void jSelectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectFileButtonActionPerformed
        csvController.selectCSV();
    }//GEN-LAST:event_jSelectFileButtonActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        csvController.saveAll();
    }//GEN-LAST:event_jSaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jListTable;
    private javax.swing.JButton jOpenExampleButton;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JButton jSelectFileButton;
    // End of variables declaration//GEN-END:variables
}
